language: cpp

matrix:
    include:
        - name: "Linux, Debug"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "Linux, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "macOS, Debug"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"
        - name: "macOS, Release"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - libgl1-mesa-dev
            - qt512-meta-full
            - unzip
            - wget
            - rpm
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.3-xenial"
    homebrew: # macOS
        packages:
            - cmake
            - git
            - qt5

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE

deploy:
    provider: releases # GitHub Releases
    api_key:
        secure: "PA0y3BN9rPQtNH7CBYALDYaG1frAEiZXzUeQybqdbgTvE/tAwoqcz/FHeiLQCBzuFRphesTD1iyJruTeLMfAnoPOGzftiFa1ttdUqlNTzXYuHCK0h+Qv2yhOEFiw4pNtEiF53TompXrcVgSjjIIJAmDOm6vJ3yvjwCoOuYE+RWpT4v8ZP6xcooyU6tytNpgsP1QhugQgS2f2ru8pOR8PMQFIP1eN+JY6U045yfET99poknGwRW03ORgqGz52V0kmGfo57Si8NYeyKDqhOKxmbXEYbjMK80aXgTYM2t2RaRtyTKPD+xhJxiymIEI3GWgVKfqf9uiRYR+OeUYqJzx+NsGhR4RQNuQ3646auck7+/3P7sIQAA5pa6PXNVZ4GBryl0pRNAK2K2CKZxKcWI+VBNvsQjYXBWqIOOlUmitZRwGSRysfGiMbyvU1g5R1ZNPhP8bspwUlWuFf6+00Fl0hmI1svir6fXHDdKAWcaYfSwoUbLzwTDt97Ia/f/HiTo56F5NFgDzCi5rgmqQ8GVZYkjL3W2fUM+Og12mjkIuTcqjk+8qkiligsSFy23teV38nIs+650u24/muWjBia8IWqH+Uy6+X4OUCg61t0YqRBji7dGA4BCaseT5yiNSx5n1wpXDszhvX655QujYVPLiRL7hNUWJLlVo1Y8+OlATV5VE="
    file: dist/qwertycoin-zero-* # path is relative to the current working directory, not to $TRAVIS_BUILD_DIR
    file_glob: true
    draft: true
    on:
        branch: master
        tags: true
        condition: $CMAKE_BUILD_TYPE = "Release"
    skip_cleanup: true
